#!/bin/bash

# run matplotlib once to generate the font cache
python -c "import matplotlib as mpl; mpl.use('Agg'); import matplotlib.pyplot as plt; fig, ax = plt.subplots(); fig.savefig('test.png')"

test -e test.png && rm test.png

# install pot (must be installed here due to cython requirement)
python -m pip install -U pot

# create default ipython profile
ipython profile create
IPYTHON_KERNEL_CONFIG="${REPO_DIR}/.ipython/profile_default/ipython_kernel_config.py"

# add EnergyFlow specific config
cat $IPYTHON_KERNEL_CONFIG ${REPO_DIR}/binder/ef_ipython_kernel_config.py > ./tmp_kernel_config.py
mv -v ./tmp_kernel_config.py $IPYTHON_KERNEL_CONFIG

# get CMS2011AJets in MOD HDF5 Format
#python ${REPO_DIR}/binder/download_CMS2011AJets.py 0.01

# install fastjet
#_PTK_START_DIR=$(pwd)

#mkdir ${REPO_DIR}/.local
#cd ${REPO_DIR}/.local
#wget -O fastjet.tar.gz http://fastjet.fr/repo/fastjet-3.3.2.tar.gz
#tar xf fastjet.tar.gz
#rm fastjet.tar.gz
#cd fastjet-3.3.2

#./configure --prefix=${REPO_DIR}/.local --enable-pyext --disable-allplugins --disable-monolithic PYTHON=python PYTHON_CONFIG=python3-config
#make
#make install

#export PYTHONPATH="$PYTHONPATH:${REPO_DIR}/.local/lib/python3.7/site-packages"
#export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:${REPO_DIR}/.local/lib"

#cd $_PTK_START_DIR
#unset _PTK_START_DIR
