name: Builds

on:
  push:
    branches:
    - master
  pull_request:
  # Run weekly at 1:23 UTC
  schedule:
  - cron: '23 1 * * 0'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Display Python version
        run: python --version

      - name: Build SDist and wheel
        run: pipx run build

      - name: Check metadata
        run: pipx run twine check --strict dist/*

      - name: List contents of sdist
        run: python -m tarfile --list dist/*.tar.gz

      - name: List contents of wheel
        run: python -m zipfile --list dist/*.whl

      - name: Upload to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: Packages
          path: dist/*

  upload_all:
    environment: pypi
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: cibw-*
          path: dist
          merge-multiple: true

      - uses: pypa/gh-action-pypi-publish@release/v1
